apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: helm-chart
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      protocol: TCP
      name: port1
      nodePort: {{ .Values.service.ports.nodePort }}
  selector:
    app: helm-chart
