name: Build + Push Docker Image and Push to K8S cluster

on:
  push:
   branches:
      - "main"
   tags:
    - "v*.*.*"
      
jobs:
     
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/diplom:${{github.ref_name }}
          
     
  k8s:
     needs: docker
     runs-on: ubuntu-latest
     steps:
      - name: Connect to K8S
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_MASTER }}
          username: ${{ secrets.DOCKER_USER }}
          key: ${{ secrets.SSH_PR }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo helm upgrade diplom-chart diplom-chart -n app --set image.tag=${{github.ref_name }}
            
 
