name: Build + Push Docker Image and Push to K8S cluster

on:
  push:
   branches:
      - "**"
   tags:
    - "v*.*.*"
      
jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            amolokov/diplom
                     
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
           
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
     
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Use repository
        uses: actions/checkout@v2
      - name: Upload repository
        uses: actions/upload-artifact@v2
        with:
          name: repository
          path: |
            ${{ github.workspace }}/diplom-chart
            ${{ github.workspace }}/Dockerfile
            ${{ github.workspace }}/README.md
            ${{ github.workspace }}/requirements.txt

  push-to-k8s:
     needs: [docker-build-and-push, setup]
     runs-on: ubuntu-latest
     steps:
      - name: Download repository
        uses: actions/download-artifact@v2
        with:
          name: repository
      - name: Add ssh
        run: |
          mkdir -p ~/.ssh/
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PUB }}" > ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_PR }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
      - name: Install helm
        run: |
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version
      - name: Lint helm charts
        run: helm lint ./diplom-chart/
      - name: Deploy to K8S
        run: |
          ssh -tt -o StrictHostKeyChecking=no ${{secrets.DOCKER_USER}}@${{secrets.IP_MASTER}}
           helm upgrade diplom-chart-chart diplom-chart -n app --set image.tag=${{ steps.meta.outputs.tags }}
           curl ${{secrets.IP_MASTER}}:31150
                       
  # push-to-k8s:
  #   needs: [docker-build-and-push, setup]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download repository
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: repository
  #     - name: Create kube config
  #       run: |
  #         mkdir -p $HOME/.kube/
  #         echo "${{ secrets.K8S_CONFIG }}" > $HOME/.kube/config
  #         chmod 600 $HOME/.kube/config
  #     - name: Install helm
  #       run: |
  #         curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
  #         tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
  #         mv linux-amd64/helm /usr/local/bin/helm
  #         helm version
  #     - name: Lint helm charts
  #       run: helm lint ./diplom-chart/
  #     - name: Deploy
  #       run: |
  #         helm upgrade --install --atomic --timeout 5s rest ./diplom-chart/ -f ./diplom-chart/values.yaml \
  #           --kube-context kubernetes-admin@cluster.local --namespace app --create-namespace \
  #           --set image.tag=${{ steps.meta.outputs.tags }}
