name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: amolokov
  DOCKER_PASSWORD: dckr_pat_VlTWbnBIv-XkM3SghNFrjJeu0z8

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: amolokov
          password: dckr_pat_VlTWbnBIv-XkM3SghNFrjJeu0z8
      - name: Build Docker image
        run: |
          docker build -t diplom:latest .
      - name: Push Docker image
        run: |
          docker tag diplom:latest amolokov/diplom:latest
          docker push amolokov/diplom:latest
